# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'version_0_7.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1118, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pictures/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.btn_raschet = QtWidgets.QPushButton(Form)
        self.btn_raschet.setObjectName("btn_raschet")
        self.horizontalLayout_7.addWidget(self.btn_raschet)
        self.btn_save_Excel = QtWidgets.QPushButton(Form)
        self.btn_save_Excel.setObjectName("btn_save_Excel")
        self.horizontalLayout_7.addWidget(self.btn_save_Excel)
        self.GrOp = QtWidgets.QCheckBox(Form)
        self.GrOp.setObjectName("GrOp")
        self.horizontalLayout_7.addWidget(self.GrOp)
        self.ZpPS = QtWidgets.QCheckBox(Form)
        self.ZpPS.setObjectName("ZpPS")
        self.horizontalLayout_7.addWidget(self.ZpPS)
        self.DZ = QtWidgets.QCheckBox(Form)
        self.DZ.setObjectName("DZ")
        self.horizontalLayout_7.addWidget(self.DZ)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.prog_inf = QtWidgets.QPushButton(Form)
        self.prog_inf.setObjectName("prog_inf")
        self.horizontalLayout_7.addWidget(self.prog_inf)
        self.horizontalLayout_7.setStretch(6, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lists = QtWidgets.QTabWidget(Form)
        self.lists.setObjectName("lists")
        self.Katal_list = QtWidgets.QWidget()
        self.Katal_list.setObjectName("Katal_list")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Katal_list)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.kat_bd = QtWidgets.QTreeView(self.Katal_list)
        self.kat_bd.setObjectName("kat_bd")
        self.verticalLayout_6.addWidget(self.kat_bd)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btn_open_file = QtWidgets.QPushButton(self.Katal_list)
        self.btn_open_file.setObjectName("btn_open_file")
        self.horizontalLayout_15.addWidget(self.btn_open_file)
        self.btn_save_file = QtWidgets.QPushButton(self.Katal_list)
        self.btn_save_file.setObjectName("btn_save_file")
        self.horizontalLayout_15.addWidget(self.btn_save_file)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.btn_open_bd = QtWidgets.QPushButton(self.Katal_list)
        self.btn_open_bd.setObjectName("btn_open_bd")
        self.horizontalLayout_15.addWidget(self.btn_open_bd)
        self.btn_save_bd = QtWidgets.QPushButton(self.Katal_list)
        self.btn_save_bd.setObjectName("btn_save_bd")
        self.horizontalLayout_15.addWidget(self.btn_save_bd)
        self.btn_savek_bd = QtWidgets.QPushButton(self.Katal_list)
        self.btn_savek_bd.setObjectName("btn_savek_bd")
        self.horizontalLayout_15.addWidget(self.btn_savek_bd)
        self.btn_newpapk_bd = QtWidgets.QPushButton(self.Katal_list)
        self.btn_newpapk_bd.setObjectName("btn_newpapk_bd")
        self.horizontalLayout_15.addWidget(self.btn_newpapk_bd)
        self.btn_rename_bd = QtWidgets.QPushButton(self.Katal_list)
        self.btn_rename_bd.setObjectName("btn_rename_bd")
        self.horizontalLayout_15.addWidget(self.btn_rename_bd)
        self.btn_del_bd = QtWidgets.QPushButton(self.Katal_list)
        self.btn_del_bd.setObjectName("btn_del_bd")
        self.horizontalLayout_15.addWidget(self.btn_del_bd)
        self.horizontalLayout_15.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.lists.addTab(self.Katal_list, "")
        self.IVL_list = QtWidgets.QWidget()
        self.IVL_list.setAccessibleName("")
        self.IVL_list.setObjectName("IVL_list")
        self.gridLayout = QtWidgets.QGridLayout(self.IVL_list)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.btn_1_clear = QtWidgets.QPushButton(self.IVL_list)
        self.btn_1_clear.setObjectName("btn_1_clear")
        self.horizontalLayout_2.addWidget(self.btn_1_clear)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.btn_1_new_v = QtWidgets.QPushButton(self.IVL_list)
        self.btn_1_new_v.setObjectName("btn_1_new_v")
        self.horizontalLayout_2.addWidget(self.btn_1_new_v)
        self.btn_1_new_y = QtWidgets.QPushButton(self.IVL_list)
        self.btn_1_new_y.setObjectName("btn_1_new_y")
        self.horizontalLayout_2.addWidget(self.btn_1_new_y)
        self.btn_1_del = QtWidgets.QPushButton(self.IVL_list)
        self.btn_1_del.setObjectName("btn_1_del")
        self.horizontalLayout_2.addWidget(self.btn_1_del)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_2.setStretch(2, 1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.table_IVL = QtWidgets.QTableWidget(self.IVL_list)
        self.table_IVL.setObjectName("table_IVL")
        self.table_IVL.setColumnCount(9)
        self.table_IVL.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_IVL.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_IVL.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_IVL.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_IVL.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_IVL.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_IVL.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_IVL.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_IVL.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_IVL.setHorizontalHeaderItem(8, item)
        self.gridLayout.addWidget(self.table_IVL, 1, 0, 1, 1)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_25 = QtWidgets.QLabel(self.IVL_list)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_33.addWidget(self.label_25)
        self.ch_1_2 = QtWidgets.QCheckBox(self.IVL_list)
        self.ch_1_2.setObjectName("ch_1_2")
        self.horizontalLayout_33.addWidget(self.ch_1_2)
        self.ch_1_3 = QtWidgets.QCheckBox(self.IVL_list)
        self.ch_1_3.setObjectName("ch_1_3")
        self.horizontalLayout_33.addWidget(self.ch_1_3)
        self.ch_1_4 = QtWidgets.QCheckBox(self.IVL_list)
        self.ch_1_4.setObjectName("ch_1_4")
        self.horizontalLayout_33.addWidget(self.ch_1_4)
        self.ch_1_5 = QtWidgets.QCheckBox(self.IVL_list)
        self.ch_1_5.setObjectName("ch_1_5")
        self.horizontalLayout_33.addWidget(self.ch_1_5)
        self.ch_1_6 = QtWidgets.QCheckBox(self.IVL_list)
        self.ch_1_6.setObjectName("ch_1_6")
        self.horizontalLayout_33.addWidget(self.ch_1_6)
        self.ch_1_7 = QtWidgets.QCheckBox(self.IVL_list)
        self.ch_1_7.setObjectName("ch_1_7")
        self.horizontalLayout_33.addWidget(self.ch_1_7)
        self.ch_1_8 = QtWidgets.QCheckBox(self.IVL_list)
        self.ch_1_8.setObjectName("ch_1_8")
        self.horizontalLayout_33.addWidget(self.ch_1_8)
        self.ch_1_9 = QtWidgets.QCheckBox(self.IVL_list)
        self.ch_1_9.setObjectName("ch_1_9")
        self.horizontalLayout_33.addWidget(self.ch_1_9)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_33, 0, 0, 1, 1)
        self.lists.addTab(self.IVL_list, "")
        self.VVL_list = QtWidgets.QWidget()
        self.VVL_list.setObjectName("VVL_list")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.VVL_list)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.table_VVL = QtWidgets.QTableWidget(self.VVL_list)
        self.table_VVL.setObjectName("table_VVL")
        self.table_VVL.setColumnCount(9)
        self.table_VVL.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_VVL.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_VVL.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_VVL.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_VVL.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_VVL.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_VVL.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_VVL.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_VVL.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_VVL.setHorizontalHeaderItem(8, item)
        self.gridLayout_2.addWidget(self.table_VVL, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.btn_2_clear = QtWidgets.QPushButton(self.VVL_list)
        self.btn_2_clear.setObjectName("btn_2_clear")
        self.horizontalLayout_5.addWidget(self.btn_2_clear)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.btn_2_new_v = QtWidgets.QPushButton(self.VVL_list)
        self.btn_2_new_v.setObjectName("btn_2_new_v")
        self.horizontalLayout_5.addWidget(self.btn_2_new_v)
        self.btn_2_new_y = QtWidgets.QPushButton(self.VVL_list)
        self.btn_2_new_y.setObjectName("btn_2_new_y")
        self.horizontalLayout_5.addWidget(self.btn_2_new_y)
        self.btn_2_del = QtWidgets.QPushButton(self.VVL_list)
        self.btn_2_del.setObjectName("btn_2_del")
        self.horizontalLayout_5.addWidget(self.btn_2_del)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.horizontalLayout_5.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_26 = QtWidgets.QLabel(self.VVL_list)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_34.addWidget(self.label_26)
        self.ch_2_2 = QtWidgets.QCheckBox(self.VVL_list)
        self.ch_2_2.setObjectName("ch_2_2")
        self.horizontalLayout_34.addWidget(self.ch_2_2)
        self.ch_2_3 = QtWidgets.QCheckBox(self.VVL_list)
        self.ch_2_3.setObjectName("ch_2_3")
        self.horizontalLayout_34.addWidget(self.ch_2_3)
        self.ch_2_4 = QtWidgets.QCheckBox(self.VVL_list)
        self.ch_2_4.setObjectName("ch_2_4")
        self.horizontalLayout_34.addWidget(self.ch_2_4)
        self.ch_2_5 = QtWidgets.QCheckBox(self.VVL_list)
        self.ch_2_5.setObjectName("ch_2_5")
        self.horizontalLayout_34.addWidget(self.ch_2_5)
        self.ch_2_6 = QtWidgets.QCheckBox(self.VVL_list)
        self.ch_2_6.setObjectName("ch_2_6")
        self.horizontalLayout_34.addWidget(self.ch_2_6)
        self.ch_2_7 = QtWidgets.QCheckBox(self.VVL_list)
        self.ch_2_7.setObjectName("ch_2_7")
        self.horizontalLayout_34.addWidget(self.ch_2_7)
        self.ch_2_8 = QtWidgets.QCheckBox(self.VVL_list)
        self.ch_2_8.setObjectName("ch_2_8")
        self.horizontalLayout_34.addWidget(self.ch_2_8)
        self.ch_2_9 = QtWidgets.QCheckBox(self.VVL_list)
        self.ch_2_9.setObjectName("ch_2_9")
        self.horizontalLayout_34.addWidget(self.ch_2_9)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem11)
        self.gridLayout_2.addLayout(self.horizontalLayout_34, 0, 0, 1, 1)
        self.lists.addTab(self.VVL_list, "")
        self.Zy_list = QtWidgets.QWidget()
        self.Zy_list.setObjectName("Zy_list")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Zy_list)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_Zy = QtWidgets.QTableWidget(self.Zy_list)
        self.table_Zy.setObjectName("table_Zy")
        self.table_Zy.setColumnCount(8)
        self.table_Zy.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zy.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zy.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zy.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zy.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zy.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zy.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zy.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zy.setHorizontalHeaderItem(7, item)
        self.gridLayout_3.addWidget(self.table_Zy, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.btn_3_clear = QtWidgets.QPushButton(self.Zy_list)
        self.btn_3_clear.setObjectName("btn_3_clear")
        self.horizontalLayout_3.addWidget(self.btn_3_clear)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.btn_3_new = QtWidgets.QPushButton(self.Zy_list)
        self.btn_3_new.setObjectName("btn_3_new")
        self.horizontalLayout_3.addWidget(self.btn_3_new)
        self.btn_3_del = QtWidgets.QPushButton(self.Zy_list)
        self.btn_3_del.setObjectName("btn_3_del")
        self.horizontalLayout_3.addWidget(self.btn_3_del)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.horizontalLayout_3.setStretch(2, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_27 = QtWidgets.QLabel(self.Zy_list)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_35.addWidget(self.label_27)
        self.ch_3_1 = QtWidgets.QCheckBox(self.Zy_list)
        self.ch_3_1.setObjectName("ch_3_1")
        self.horizontalLayout_35.addWidget(self.ch_3_1)
        self.ch_3_2 = QtWidgets.QCheckBox(self.Zy_list)
        self.ch_3_2.setObjectName("ch_3_2")
        self.horizontalLayout_35.addWidget(self.ch_3_2)
        self.ch_3_3 = QtWidgets.QCheckBox(self.Zy_list)
        self.ch_3_3.setObjectName("ch_3_3")
        self.horizontalLayout_35.addWidget(self.ch_3_3)
        self.ch_3_4 = QtWidgets.QCheckBox(self.Zy_list)
        self.ch_3_4.setObjectName("ch_3_4")
        self.horizontalLayout_35.addWidget(self.ch_3_4)
        self.ch_3_5 = QtWidgets.QCheckBox(self.Zy_list)
        self.ch_3_5.setObjectName("ch_3_5")
        self.horizontalLayout_35.addWidget(self.ch_3_5)
        self.ch_3_6 = QtWidgets.QCheckBox(self.Zy_list)
        self.ch_3_6.setObjectName("ch_3_6")
        self.horizontalLayout_35.addWidget(self.ch_3_6)
        self.ch_3_7 = QtWidgets.QCheckBox(self.Zy_list)
        self.ch_3_7.setObjectName("ch_3_7")
        self.horizontalLayout_35.addWidget(self.ch_3_7)
        self.ch_3_8 = QtWidgets.QCheckBox(self.Zy_list)
        self.ch_3_8.setObjectName("ch_3_8")
        self.horizontalLayout_35.addWidget(self.ch_3_8)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem15)
        self.gridLayout_3.addLayout(self.horizontalLayout_35, 0, 0, 1, 1)
        self.lists.addTab(self.Zy_list, "")
        self.Zytr_list = QtWidgets.QWidget()
        self.Zytr_list.setObjectName("Zytr_list")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Zytr_list)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.btn_4_clear = QtWidgets.QPushButton(self.Zytr_list)
        self.btn_4_clear.setObjectName("btn_4_clear")
        self.horizontalLayout_4.addWidget(self.btn_4_clear)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.btn_4_new = QtWidgets.QPushButton(self.Zytr_list)
        self.btn_4_new.setObjectName("btn_4_new")
        self.horizontalLayout_4.addWidget(self.btn_4_new)
        self.btn_4_del = QtWidgets.QPushButton(self.Zytr_list)
        self.btn_4_del.setObjectName("btn_4_del")
        self.horizontalLayout_4.addWidget(self.btn_4_del)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.horizontalLayout_4.setStretch(2, 1)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.table_Zytr = QtWidgets.QTableWidget(self.Zytr_list)
        self.table_Zytr.setObjectName("table_Zytr")
        self.table_Zytr.setColumnCount(5)
        self.table_Zytr.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zytr.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zytr.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zytr.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zytr.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zytr.setHorizontalHeaderItem(4, item)
        self.gridLayout_4.addWidget(self.table_Zytr, 2, 0, 1, 1)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_28 = QtWidgets.QLabel(self.Zytr_list)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_36.addWidget(self.label_28)
        self.ch_4_1 = QtWidgets.QCheckBox(self.Zytr_list)
        self.ch_4_1.setObjectName("ch_4_1")
        self.horizontalLayout_36.addWidget(self.ch_4_1)
        self.ch_4_2 = QtWidgets.QCheckBox(self.Zytr_list)
        self.ch_4_2.setObjectName("ch_4_2")
        self.horizontalLayout_36.addWidget(self.ch_4_2)
        self.ch_4_3 = QtWidgets.QCheckBox(self.Zytr_list)
        self.ch_4_3.setObjectName("ch_4_3")
        self.horizontalLayout_36.addWidget(self.ch_4_3)
        self.ch_4_4 = QtWidgets.QCheckBox(self.Zytr_list)
        self.ch_4_4.setObjectName("ch_4_4")
        self.horizontalLayout_36.addWidget(self.ch_4_4)
        self.ch_4_5 = QtWidgets.QCheckBox(self.Zytr_list)
        self.ch_4_5.setObjectName("ch_4_5")
        self.horizontalLayout_36.addWidget(self.ch_4_5)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem19)
        self.gridLayout_4.addLayout(self.horizontalLayout_36, 1, 0, 1, 1)
        self.lists.addTab(self.Zytr_list, "")
        self.Zvl_list = QtWidgets.QWidget()
        self.Zvl_list.setObjectName("Zvl_list")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Zvl_list)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem20)
        self.btn_5_clear = QtWidgets.QPushButton(self.Zvl_list)
        self.btn_5_clear.setObjectName("btn_5_clear")
        self.horizontalLayout_6.addWidget(self.btn_5_clear)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem21)
        self.btn_5_new = QtWidgets.QPushButton(self.Zvl_list)
        self.btn_5_new.setObjectName("btn_5_new")
        self.horizontalLayout_6.addWidget(self.btn_5_new)
        self.btn_5_del = QtWidgets.QPushButton(self.Zvl_list)
        self.btn_5_del.setObjectName("btn_5_del")
        self.horizontalLayout_6.addWidget(self.btn_5_del)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem22)
        self.horizontalLayout_6.setStretch(2, 1)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.table_Zvl = QtWidgets.QTableWidget(self.Zvl_list)
        self.table_Zvl.setObjectName("table_Zvl")
        self.table_Zvl.setColumnCount(9)
        self.table_Zvl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zvl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zvl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zvl.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zvl.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zvl.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zvl.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zvl.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zvl.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zvl.setHorizontalHeaderItem(8, item)
        self.gridLayout_5.addWidget(self.table_Zvl, 1, 0, 1, 1)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_29 = QtWidgets.QLabel(self.Zvl_list)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_37.addWidget(self.label_29)
        self.ch_5_1 = QtWidgets.QCheckBox(self.Zvl_list)
        self.ch_5_1.setObjectName("ch_5_1")
        self.horizontalLayout_37.addWidget(self.ch_5_1)
        self.ch_5_2 = QtWidgets.QCheckBox(self.Zvl_list)
        self.ch_5_2.setObjectName("ch_5_2")
        self.horizontalLayout_37.addWidget(self.ch_5_2)
        self.ch_5_3 = QtWidgets.QCheckBox(self.Zvl_list)
        self.ch_5_3.setObjectName("ch_5_3")
        self.horizontalLayout_37.addWidget(self.ch_5_3)
        self.ch_5_4 = QtWidgets.QCheckBox(self.Zvl_list)
        self.ch_5_4.setObjectName("ch_5_4")
        self.horizontalLayout_37.addWidget(self.ch_5_4)
        self.ch_5_5 = QtWidgets.QCheckBox(self.Zvl_list)
        self.ch_5_5.setObjectName("ch_5_5")
        self.horizontalLayout_37.addWidget(self.ch_5_5)
        self.ch_5_6 = QtWidgets.QCheckBox(self.Zvl_list)
        self.ch_5_6.setObjectName("ch_5_6")
        self.horizontalLayout_37.addWidget(self.ch_5_6)
        self.ch_5_7 = QtWidgets.QCheckBox(self.Zvl_list)
        self.ch_5_7.setObjectName("ch_5_7")
        self.horizontalLayout_37.addWidget(self.ch_5_7)
        self.ch_5_8 = QtWidgets.QCheckBox(self.Zvl_list)
        self.ch_5_8.setObjectName("ch_5_8")
        self.horizontalLayout_37.addWidget(self.ch_5_8)
        self.ch_5_9 = QtWidgets.QCheckBox(self.Zvl_list)
        self.ch_5_9.setObjectName("ch_5_9")
        self.horizontalLayout_37.addWidget(self.ch_5_9)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem23)
        self.gridLayout_5.addLayout(self.horizontalLayout_37, 0, 0, 1, 1)
        self.lists.addTab(self.Zvl_list, "")
        self.Gr_list = QtWidgets.QWidget()
        self.Gr_list.setObjectName("Gr_list")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Gr_list)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.tx_op1 = QtWidgets.QSpinBox(self.Gr_list)
        self.tx_op1.setMaximum(9999)
        self.tx_op1.setObjectName("tx_op1")
        self.horizontalLayout_38.addWidget(self.tx_op1)
        self.tx_op2 = QtWidgets.QSpinBox(self.Gr_list)
        self.tx_op2.setMaximum(9999)
        self.tx_op2.setObjectName("tx_op2")
        self.horizontalLayout_38.addWidget(self.tx_op2)
        self.btn_ych_open = QtWidgets.QPushButton(self.Gr_list)
        self.btn_ych_open.setObjectName("btn_ych_open")
        self.horizontalLayout_38.addWidget(self.btn_ych_open)
        self.btn_ych_close = QtWidgets.QPushButton(self.Gr_list)
        self.btn_ych_close.setObjectName("btn_ych_close")
        self.horizontalLayout_38.addWidget(self.btn_ych_close)
        self.btn_pz1 = QtWidgets.QPushButton(self.Gr_list)
        self.btn_pz1.setObjectName("btn_pz1")
        self.horizontalLayout_38.addWidget(self.btn_pz1)
        self.btn_pz2 = QtWidgets.QPushButton(self.Gr_list)
        self.btn_pz2.setObjectName("btn_pz2")
        self.horizontalLayout_38.addWidget(self.btn_pz2)
        self.btn_pz1_zapr = QtWidgets.QPushButton(self.Gr_list)
        self.btn_pz1_zapr.setObjectName("btn_pz1_zapr")
        self.horizontalLayout_38.addWidget(self.btn_pz1_zapr)
        self.btn_pz2_zapr = QtWidgets.QPushButton(self.Gr_list)
        self.btn_pz2_zapr.setObjectName("btn_pz2_zapr")
        self.horizontalLayout_38.addWidget(self.btn_pz2_zapr)
        self.verticalLayout_2.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_40.addLayout(self.verticalLayout_2)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem24)
        self.verticalLayout_10.addLayout(self.horizontalLayout_40)
        self.TWGr = QtWidgets.QTabWidget(self.Gr_list)
        self.TWGr.setObjectName("TWGr")
        self.verticalLayout_10.addWidget(self.TWGr)
        self.lists.addTab(self.Gr_list, "")
        self.Sxsb_list = QtWidgets.QWidget()
        self.Sxsb_list.setObjectName("Sxsb_list")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Sxsb_list)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.foolwindow = QtWidgets.QPushButton(self.Sxsb_list)
        self.foolwindow.setObjectName("foolwindow")
        self.horizontalLayout_16.addWidget(self.foolwindow)
        self.natsize = QtWidgets.QPushButton(self.Sxsb_list)
        self.natsize.setObjectName("natsize")
        self.horizontalLayout_16.addWidget(self.natsize)
        self.zoommax = QtWidgets.QPushButton(self.Sxsb_list)
        self.zoommax.setObjectName("zoommax")
        self.horizontalLayout_16.addWidget(self.zoommax)
        self.zoommin = QtWidgets.QPushButton(self.Sxsb_list)
        self.zoommin.setObjectName("zoommin")
        self.horizontalLayout_16.addWidget(self.zoommin)
        self.label_4 = QtWidgets.QLabel(self.Sxsb_list)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_16.addWidget(self.label_4)
        self.title_f_s = QtWidgets.QSpinBox(self.Sxsb_list)
        self.title_f_s.setObjectName("title_f_s")
        self.horizontalLayout_16.addWidget(self.title_f_s)
        self.label_5 = QtWidgets.QLabel(self.Sxsb_list)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_16.addWidget(self.label_5)
        self.f_s = QtWidgets.QSpinBox(self.Sxsb_list)
        self.f_s.setObjectName("f_s")
        self.horizontalLayout_16.addWidget(self.f_s)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem25)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.PaintArea = QtWidgets.QWidget(self.Sxsb_list)
        self.PaintArea.setObjectName("PaintArea")
        self.verticalLayout_12.addWidget(self.PaintArea)
        self.verticalLayout_12.setStretch(1, 1)
        self.lists.addTab(self.Sxsb_list, "")
        self.Ot_list = QtWidgets.QWidget()
        self.Ot_list.setObjectName("Ot_list")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.Ot_list)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.Ot_list)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 345, 789))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem26)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem27)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.name_vl = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.name_vl.setObjectName("name_vl")
        self.verticalLayout_3.addWidget(self.name_vl)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.btn_Oid = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_Oid.setObjectName("btn_Oid")
        self.horizontalLayout_9.addWidget(self.btn_Oid)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem28)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.N_sxem = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.N_sxem.setObjectName("N_sxem")
        self.N_sxem.addItem("")
        self.N_sxem.addItem("")
        self.N_sxem.addItem("")
        self.N_sxem.addItem("")
        self.horizontalLayout_8.addWidget(self.N_sxem)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.S_one_var = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.S_one_var.setObjectName("S_one_var")
        self.horizontalLayout_8.addWidget(self.S_one_var)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem29)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(5, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem30)
        self.tablepo = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.tablepo.setObjectName("tablepo")
        self.tablepo.addItem("")
        self.tablepo.addItem("")
        self.tablepo.addItem("")
        self.horizontalLayout_32.addWidget(self.tablepo)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem31)
        self.horizontalLayout_32.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.zy_om = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.zy_om.setObjectName("zy_om")
        self.horizontalLayout_12.addWidget(self.zy_om)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem32)
        self.btn_S_one = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_S_one.setObjectName("btn_S_one")
        self.horizontalLayout_11.addWidget(self.btn_S_one)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem33)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem34)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_20.addWidget(self.label_15)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem35)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.Ch_one_sch4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.Ch_one_sch4.setObjectName("Ch_one_sch4")
        self.verticalLayout_3.addWidget(self.Ch_one_sch4)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem36)
        self.Sch_val = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        self.Sch_val.setObjectName("Sch_val")
        self.Sch_val.addItem("")
        self.Sch_val.addItem("")
        self.Sch_val.addItem("")
        self.Sch_val.addItem("")
        self.Sch_val.addItem("")
        self.Sch_val.addItem("")
        self.Sch_val.addItem("")
        self.horizontalLayout_22.addWidget(self.Sch_val)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem37)
        self.horizontalLayout_22.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16)
        self.ValPZ1 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.ValPZ1.setObjectName("ValPZ1")
        self.horizontalLayout_19.addWidget(self.ValPZ1)
        self.ValPZ2 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.ValPZ2.setObjectName("ValPZ2")
        self.horizontalLayout_19.addWidget(self.ValPZ2)
        self.horizontalLayout_19.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem38)
        self.btn_all_sch = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_all_sch.setObjectName("btn_all_sch")
        self.horizontalLayout_21.addWidget(self.btn_all_sch)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem39)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem40)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_25.addWidget(self.label_19)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem41)
        self.verticalLayout_3.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_24.addWidget(self.label_18)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem42)
        self.ValSZ = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.ValSZ.setObjectName("ValSZ")
        self.horizontalLayout_24.addWidget(self.ValSZ)
        self.verticalLayout_3.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_26.addWidget(self.label_20)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem43)
        self.ValMaxSZ = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.ValMaxSZ.setObjectName("ValMaxSZ")
        self.horizontalLayout_26.addWidget(self.ValMaxSZ)
        self.verticalLayout_3.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_27.addWidget(self.label_21)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem44)
        self.ValMinSZ = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.ValMinSZ.setObjectName("ValMinSZ")
        self.horizontalLayout_27.addWidget(self.ValMinSZ)
        self.verticalLayout_3.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_28.addWidget(self.label_22)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem45)
        self.ValEpsSZ = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.ValEpsSZ.setObjectName("ValEpsSZ")
        self.horizontalLayout_28.addWidget(self.ValEpsSZ)
        self.verticalLayout_3.addLayout(self.horizontalLayout_28)
        self.Ch_too_sz = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.Ch_too_sz.setObjectName("Ch_too_sz")
        self.verticalLayout_3.addWidget(self.Ch_too_sz)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_29.addWidget(self.label_23)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem46)
        self.ValTooSZ = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_3)
        self.ValTooSZ.setObjectName("ValTooSZ")
        self.horizontalLayout_29.addWidget(self.ValTooSZ)
        self.verticalLayout_3.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_23.addWidget(self.label_17)
        self.btn_SZ_generate = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_SZ_generate.setObjectName("btn_SZ_generate")
        self.horizontalLayout_23.addWidget(self.btn_SZ_generate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem47)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_30.addWidget(self.label_24)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem48)
        self.verticalLayout_3.addLayout(self.horizontalLayout_30)
        self.Ch_one_file = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.Ch_one_file.setObjectName("Ch_one_file")
        self.verticalLayout_3.addWidget(self.Ch_one_file)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btn_sof = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_sof.setObjectName("btn_sof")
        self.verticalLayout_9.addWidget(self.btn_sof)
        self.btn_op_temp = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_op_temp.setObjectName("btn_op_temp")
        self.verticalLayout_9.addWidget(self.btn_op_temp)
        self.horizontalLayout_31.addLayout(self.verticalLayout_9)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem49)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_ch_list = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_ch_list.setObjectName("btn_ch_list")
        self.verticalLayout_11.addWidget(self.btn_ch_list)
        self.btn_cl_onfile = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_cl_onfile.setObjectName("btn_cl_onfile")
        self.verticalLayout_11.addWidget(self.btn_cl_onfile)
        self.horizontalLayout_31.addLayout(self.verticalLayout_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_31)
        self.Ch_dbl_vl = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.Ch_dbl_vl.setObjectName("Ch_dbl_vl")
        self.verticalLayout_3.addWidget(self.Ch_dbl_vl)
        self.Ch_use_templ = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.Ch_use_templ.setObjectName("Ch_use_templ")
        self.verticalLayout_3.addWidget(self.Ch_use_templ)
        spacerItem50 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem50)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_17.addWidget(self.scrollArea_2)
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem51)
        self.scrollArea = QtWidgets.QScrollArea(self.Ot_list)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 327, 785))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem52)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem53)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.Ch_sxzgr = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.Ch_sxzgr.setObjectName("Ch_sxzgr")
        self.verticalLayout_13.addWidget(self.Ch_sxzgr)
        self.ch_miss = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.ch_miss.setObjectName("ch_miss")
        self.verticalLayout_13.addWidget(self.ch_miss)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_13.addWidget(self.label_12)
        self.Dop_V = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.Dop_V.setObjectName("Dop_V")
        self.verticalLayout_13.addWidget(self.Dop_V)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.Koef_gr = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.Koef_gr.setObjectName("Koef_gr")
        self.verticalLayout_13.addWidget(self.Koef_gr)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Ch_A = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Ch_A.setFont(font)
        self.Ch_A.setObjectName("Ch_A")
        self.verticalLayout_4.addWidget(self.Ch_A)
        self.Ch_B = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Ch_B.setFont(font)
        self.Ch_B.setObjectName("Ch_B")
        self.verticalLayout_4.addWidget(self.Ch_B)
        self.Ch_C = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Ch_C.setFont(font)
        self.Ch_C.setObjectName("Ch_C")
        self.verticalLayout_4.addWidget(self.Ch_C)
        self.Ch_Tr = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Ch_Tr.setFont(font)
        self.Ch_Tr.setObjectName("Ch_Tr")
        self.verticalLayout_4.addWidget(self.Ch_Tr)
        self.horizontalLayout_14.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Ln_A = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.Ln_A.setObjectName("Ln_A")
        self.verticalLayout_5.addWidget(self.Ln_A)
        self.Ln_B = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.Ln_B.setObjectName("Ln_B")
        self.verticalLayout_5.addWidget(self.Ln_B)
        self.Ln_C = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.Ln_C.setObjectName("Ln_C")
        self.verticalLayout_5.addWidget(self.Ln_C)
        self.Ln_Tr = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.Ln_Tr.setObjectName("Ln_Tr")
        self.verticalLayout_5.addWidget(self.Ln_Tr)
        self.horizontalLayout_14.addLayout(self.verticalLayout_5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_13.addWidget(self.label_6)
        self.grunt = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.grunt.setObjectName("grunt")
        self.verticalLayout_13.addWidget(self.grunt)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.Kesh_VL = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.Kesh_VL.setObjectName("Kesh_VL")
        self.verticalLayout_13.addWidget(self.Kesh_VL)
        self.Kesh_ZY = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.Kesh_ZY.setObjectName("Kesh_ZY")
        self.verticalLayout_13.addWidget(self.Kesh_ZY)
        self.Kesh_P = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.Kesh_P.setObjectName("Kesh_P")
        self.verticalLayout_13.addWidget(self.Kesh_P)
        self.Kesh_R = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.Kesh_R.setObjectName("Kesh_R")
        self.verticalLayout_13.addWidget(self.Kesh_R)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.btn_rl = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_rl.setObjectName("btn_rl")
        self.horizontalLayout_18.addWidget(self.btn_rl)
        self.btn_clear_kesh = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_clear_kesh.setObjectName("btn_clear_kesh")
        self.horizontalLayout_18.addWidget(self.btn_clear_kesh)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.kol_files = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kol_files.setFont(font)
        self.kol_files.setObjectName("kol_files")
        self.verticalLayout_13.addWidget(self.kol_files)
        self.size_files = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.size_files.setFont(font)
        self.size_files.setObjectName("size_files")
        self.verticalLayout_13.addWidget(self.size_files)
        spacerItem54 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem54)
        self.verticalLayout_7.addLayout(self.verticalLayout_13)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_17.addWidget(self.scrollArea)
        self.verticalLayout_14.addLayout(self.horizontalLayout_17)
        self.lists.addTab(self.Ot_list, "")
        self.horizontalLayout.addWidget(self.lists)
        spacerItem55 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem55)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem56 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem56)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Form)
        self.lists.setCurrentIndex(0)
        self.TWGr.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Расчет наведенного напряжения v0.7"))
        self.btn_raschet.setText(_translate("Form", "Расчитать"))
        self.btn_save_Excel.setText(_translate("Form", "Сохранить в Excel"))
        self.GrOp.setText(_translate("Form", "Откл. гран. оп."))
        self.ZpPS.setText(_translate("Form", "Запр. раб. ПС"))
        self.DZ.setText(_translate("Form", "Уст. ДЗ"))
        self.prog_inf.setText(_translate("Form", "О программе"))
        self.btn_open_file.setText(_translate("Form", "Открыть файл"))
        self.btn_save_file.setText(_translate("Form", "Сохранить в файл"))
        self.btn_open_bd.setText(_translate("Form", "Открыть"))
        self.btn_save_bd.setText(_translate("Form", "Сохранить"))
        self.btn_savek_bd.setText(_translate("Form", "Сохранить как"))
        self.btn_newpapk_bd.setText(_translate("Form", "Добавить папку"))
        self.btn_rename_bd.setText(_translate("Form", "Переименовать"))
        self.btn_del_bd.setText(_translate("Form", "Удалить"))
        self.lists.setTabText(self.lists.indexOf(self.Katal_list), _translate("Form", "Каталог"))
        self.btn_1_clear.setText(_translate("Form", "Очистить окно"))
        self.btn_1_new_v.setText(_translate("Form", "Добавить ветвь"))
        self.btn_1_new_y.setText(_translate("Form", "Добавить участок"))
        self.btn_1_del.setText(_translate("Form", "Удалить"))
        item = self.table_IVL.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Название ветви"))
        item = self.table_IVL.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Длина участка, км"))
        item = self.table_IVL.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Первая опора"))
        item = self.table_IVL.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Последняя опора"))
        item = self.table_IVL.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Фазировка"))
        item = self.table_IVL.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Тип опоры"))
        item = self.table_IVL.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Марка провода"))
        item = self.table_IVL.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Марка тросса №1"))
        item = self.table_IVL.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Марка тросса №2"))
        self.label_25.setText(_translate("Form", "Копировать/Вставить:"))
        self.ch_1_2.setText(_translate("Form", "2"))
        self.ch_1_3.setText(_translate("Form", "3"))
        self.ch_1_4.setText(_translate("Form", "4"))
        self.ch_1_5.setText(_translate("Form", "5"))
        self.ch_1_6.setText(_translate("Form", "6"))
        self.ch_1_7.setText(_translate("Form", "7"))
        self.ch_1_8.setText(_translate("Form", "8"))
        self.ch_1_9.setText(_translate("Form", "9"))
        self.lists.setTabText(self.lists.indexOf(self.IVL_list), _translate("Form", "РВЛ"))
        item = self.table_VVL.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Название ветви"))
        item = self.table_VVL.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Первая опора"))
        item = self.table_VVL.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Последняя опора"))
        item = self.table_VVL.horizontalHeaderItem(3)
        item.setText(_translate("Form", "U, кВ/Растояние сближения, м"))
        item = self.table_VVL.horizontalHeaderItem(4)
        item.setText(_translate("Form", "P, МВт/Фазировка"))
        item = self.table_VVL.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Q, Мвар/Тип опоры"))
        item = self.table_VVL.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Направл. P/Марка провода"))
        item = self.table_VVL.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Марка тросса №1"))
        item = self.table_VVL.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Марка тросса №2"))
        self.btn_2_clear.setText(_translate("Form", "Очистить окно"))
        self.btn_2_new_v.setText(_translate("Form", "Добавить ВЛ"))
        self.btn_2_new_y.setText(_translate("Form", "Добавить участок"))
        self.btn_2_del.setText(_translate("Form", "Удалить "))
        self.label_26.setText(_translate("Form", "Копировать/Вставить:"))
        self.ch_2_2.setText(_translate("Form", "2"))
        self.ch_2_3.setText(_translate("Form", "3"))
        self.ch_2_4.setText(_translate("Form", "4"))
        self.ch_2_5.setText(_translate("Form", "5"))
        self.ch_2_6.setText(_translate("Form", "6"))
        self.ch_2_7.setText(_translate("Form", "7"))
        self.ch_2_8.setText(_translate("Form", "8"))
        self.ch_2_9.setText(_translate("Form", "9"))
        self.lists.setTabText(self.lists.indexOf(self.VVL_list), _translate("Form", "ВВЛ"))
        item = self.table_Zy.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Участок Nn"))
        item = self.table_Zy.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Участок Nk"))
        item = self.table_Zy.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Опора №"))
        item = self.table_Zy.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Сопротивление заземленя, Ом"))
        item = self.table_Zy.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Заземлено фаз, Nф"))
        item = self.table_Zy.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Фаза №1"))
        item = self.table_Zy.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Фаза №2"))
        item = self.table_Zy.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Тип заземления"))
        self.btn_3_clear.setText(_translate("Form", "Очистить окно"))
        self.btn_3_new.setText(_translate("Form", "Добавить заземлитель"))
        self.btn_3_del.setText(_translate("Form", "Удалить"))
        self.label_27.setText(_translate("Form", "Копировать/Вставить:"))
        self.ch_3_1.setText(_translate("Form", "1"))
        self.ch_3_2.setText(_translate("Form", "2"))
        self.ch_3_3.setText(_translate("Form", "3"))
        self.ch_3_4.setText(_translate("Form", "4"))
        self.ch_3_5.setText(_translate("Form", "5"))
        self.ch_3_6.setText(_translate("Form", "6"))
        self.ch_3_7.setText(_translate("Form", "7"))
        self.ch_3_8.setText(_translate("Form", "8"))
        self.lists.setTabText(self.lists.indexOf(self.Zy_list), _translate("Form", "Заземление в точках"))
        self.btn_4_clear.setText(_translate("Form", "Очистить окно"))
        self.btn_4_new.setText(_translate("Form", "Добавить участок"))
        self.btn_4_del.setText(_translate("Form", "Удалить"))
        item = self.table_Zytr.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Участок Nn"))
        item = self.table_Zytr.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Участок Nk"))
        item = self.table_Zytr.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Первая опора"))
        item = self.table_Zytr.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Последняя опора"))
        item = self.table_Zytr.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Сопротивление заземления, Ом"))
        self.label_28.setText(_translate("Form", "Копировать/Вставить:"))
        self.ch_4_1.setText(_translate("Form", "1"))
        self.ch_4_2.setText(_translate("Form", "2"))
        self.ch_4_3.setText(_translate("Form", "3"))
        self.ch_4_4.setText(_translate("Form", "4"))
        self.ch_4_5.setText(_translate("Form", "5"))
        self.lists.setTabText(self.lists.indexOf(self.Zytr_list), _translate("Form", "Заземление тросов опор РВЛ"))
        self.btn_5_clear.setText(_translate("Form", "Очистить окно"))
        self.btn_5_new.setText(_translate("Form", "Добавить ВЛ"))
        self.btn_5_del.setText(_translate("Form", "Удалить"))
        item = self.table_Zvl.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Сопротивление заземления, Ом"))
        item = self.table_Zvl.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Длина пердыдущего участка"))
        item = self.table_Zvl.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Кол. опор предыдущего уч."))
        item = self.table_Zvl.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Длина последующего участка"))
        item = self.table_Zvl.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Кол. опор последующего уч."))
        item = self.table_Zvl.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Фазировка"))
        item = self.table_Zvl.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Тип опор"))
        item = self.table_Zvl.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Марка тросса №1"))
        item = self.table_Zvl.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Марка тросса №2"))
        self.label_29.setText(_translate("Form", "Копировать/Вставить:"))
        self.ch_5_1.setText(_translate("Form", "1"))
        self.ch_5_2.setText(_translate("Form", "2"))
        self.ch_5_3.setText(_translate("Form", "3"))
        self.ch_5_4.setText(_translate("Form", "4"))
        self.ch_5_5.setText(_translate("Form", "5"))
        self.ch_5_6.setText(_translate("Form", "6"))
        self.ch_5_7.setText(_translate("Form", "7"))
        self.ch_5_8.setText(_translate("Form", "8"))
        self.ch_5_9.setText(_translate("Form", "9"))
        self.lists.setTabText(self.lists.indexOf(self.Zvl_list), _translate("Form", "Заземление тросов опор ВВЛ"))
        self.btn_ych_open.setText(_translate("Form", "Разрешить"))
        self.btn_ych_close.setText(_translate("Form", "Запретить"))
        self.btn_pz1.setText(_translate("Form", "ПЗ 1"))
        self.btn_pz2.setText(_translate("Form", "ПЗ 2"))
        self.btn_pz1_zapr.setText(_translate("Form", "Запр. ПС 1"))
        self.btn_pz2_zapr.setText(_translate("Form", "Запр. ПС 2"))
        self.lists.setTabText(self.lists.indexOf(self.Gr_list), _translate("Form", "Графики"))
        self.foolwindow.setText(_translate("Form", "На весь экран"))
        self.natsize.setText(_translate("Form", "Натуральный размер"))
        self.zoommax.setText(_translate("Form", "Увеличить"))
        self.zoommin.setText(_translate("Form", "Уменьшить"))
        self.label_4.setText(_translate("Form", "Текст заголовка"))
        self.label_5.setText(_translate("Form", "Текст картинки"))
        self.lists.setTabText(self.lists.indexOf(self.Sxsb_list), _translate("Form", "Схема сближения"))
        self.label_9.setText(_translate("Form", "Отчёт"))
        self.label.setText(_translate("Form", "Наименование расчетной линии:"))
        self.label_2.setText(_translate("Form", "Основные исходные данные"))
        self.btn_Oid.setText(_translate("Form", "Сохранить"))
        self.label_10.setText(_translate("Form", "Результаты расчёта:"))
        self.label_3.setText(_translate("Form", "Схема"))
        self.N_sxem.setItemText(0, _translate("Form", "№ 1"))
        self.N_sxem.setItemText(1, _translate("Form", "№ 2"))
        self.N_sxem.setItemText(2, _translate("Form", "№ 3"))
        self.N_sxem.setItemText(3, _translate("Form", "№ 4"))
        self.label_8.setText(_translate("Form", "."))
        self.tablepo.setItemText(0, _translate("Form", "Выводить таблицы и эпюры"))
        self.tablepo.setItemText(1, _translate("Form", "Выводить таблицы"))
        self.tablepo.setItemText(2, _translate("Form", "Выводить эпюры"))
        self.label_7.setText(_translate("Form", "Сопротивление БЗ, Ом"))
        self.btn_S_one.setText(_translate("Form", "Сохранить"))
        self.label_15.setText(_translate("Form", "Генерация набора инструкций"))
        self.Ch_one_sch4.setText(_translate("Form", "Генерировать только одну Схему №4"))
        self.Sch_val.setItemText(0, _translate("Form", "Все схемы"))
        self.Sch_val.setItemText(1, _translate("Form", "Схема №1"))
        self.Sch_val.setItemText(2, _translate("Form", "Схема №2"))
        self.Sch_val.setItemText(3, _translate("Form", "Схема №4"))
        self.Sch_val.setItemText(4, _translate("Form", "Схема №1,2"))
        self.Sch_val.setItemText(5, _translate("Form", "Схема №1,4"))
        self.Sch_val.setItemText(6, _translate("Form", "Схема №2,4"))
        self.label_16.setText(_translate("Form", "Номера строк основных ПЗ"))
        self.btn_all_sch.setText(_translate("Form", "Сохранить"))
        self.label_19.setText(_translate("Form", "Автоподбор СЗ"))
        self.label_18.setText(_translate("Form", "Максимальное количество СЗ"))
        self.label_20.setText(_translate("Form", "Верхний диапазон для СЗ, Ом"))
        self.label_21.setText(_translate("Form", "Нижний диапозон для СЗ, Ом"))
        self.label_22.setText(_translate("Form", "Точность подбора СЗ, Ом"))
        self.Ch_too_sz.setText(_translate("Form", "Принудительная повторная проверка СЗ"))
        self.label_23.setText(_translate("Form", "Количество повторных проверок"))
        self.label_17.setText(_translate("Form", "Подбор мест для установки СЗ"))
        self.btn_SZ_generate.setText(_translate("Form", "Пуск"))
        self.label_24.setText(_translate("Form", "Инструкции в одном файле"))
        self.Ch_one_file.setText(_translate("Form", "Собирать инструкции в один файл"))
        self.btn_sof.setText(_translate("Form", "Сохранить"))
        self.btn_op_temp.setText(_translate("Form", "Загрузить шаблон"))
        self.btn_ch_list.setText(_translate("Form", "Просмотр добавленых ВЛ"))
        self.btn_cl_onfile.setText(_translate("Form", "Очистить файл"))
        self.Ch_dbl_vl.setText(_translate("Form", "Разрешить повторение ВЛ"))
        self.Ch_use_templ.setText(_translate("Form", "Использовать шаблон"))
        self.label_11.setText(_translate("Form", "Настройки"))
        self.Ch_sxzgr.setText(_translate("Form", "Схема заземления во вкледке графиков"))
        self.ch_miss.setText(_translate("Form", "Указывать место и тип ошибки в исходных данных"))
        self.label_12.setText(_translate("Form", "Допустимое разрешённое напряжение:"))
        self.label_13.setText(_translate("Form", "Коэффициент маcштаба графика:"))
        self.Ch_A.setText(_translate("Form", "Фаза А"))
        self.Ch_B.setText(_translate("Form", "Фаза В"))
        self.Ch_C.setText(_translate("Form", "Фаза С"))
        self.Ch_Tr.setText(_translate("Form", "Трос"))
        self.label_6.setText(_translate("Form", "Удельное сопротивление земли Ом м:"))
        self.label_14.setText(_translate("Form", "Кэширование расчётов"))
        self.Kesh_VL.setText(_translate("Form", "Кэширование схем ВЛ"))
        self.Kesh_ZY.setText(_translate("Form", "Кэширование заземления ВЛ"))
        self.Kesh_P.setText(_translate("Form", "Кэширование мощностей ВЛ"))
        self.Kesh_R.setText(_translate("Form", "Кэширование результатов расчётов"))
        self.btn_rl.setText(_translate("Form", "Обновить"))
        self.btn_clear_kesh.setText(_translate("Form", "Очистить кэш"))
        self.kol_files.setText(_translate("Form", "Файлов, шт:"))
        self.size_files.setText(_translate("Form", "Резмер кэша, МБ:"))
        self.lists.setTabText(self.lists.indexOf(self.Ot_list), _translate("Form", "Отчет"))

